name: Copy Instance Content
on:
  pull_request:
    types: [opened,reopened]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        ruby-version: [2.6]
        dev-environment: [profservices]

    steps:
    - name: Checkout the branch requesting the pull request
      uses: actions/checkout@v2
      with:
        ref: ${{github.head_ref}}
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install Gazer
      run: gem install gazer
    - name: Install Rename
      run: sudo apt install rename
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Looker Deployer
      run: |
        python -m pip install --upgrade pip
        pip install looker-deployer
    - name: Create Looker ini File
      run: |
          cat << EOF > looker.ini
          [profservices]
          base_url=https://profservices.dev.looker.com:19999
          client_id=${{ secrets.PROFSERVICES_CLIENT_ID }}
          client_secret=${{ secrets.PROFSERVICES_SECRET }}
          verify_ssl=True 
          
          [saleseng]
          base_url=https://saleseng.dev.looker.com:19999
          client_id=${{ secrets.SALESENG_CLIENT_ID }}
          client_secret=${{ secrets.SALESENG_SECRET }}
          verify_ssl=True 
          EOF
    - name: Export content to instance_content_new
      run: |
        ldeploy content export --folders 1 --env ${{ matrix.dev-environment }} --ini looker.ini --local-target ./instance_content_new
    - name: Remove spaces in file and directory names from exported content new
      run: |
        find -name "* *" -print0 | sort -rz | while read -d $'\0' f; do mv -v "$f" "$(dirname "$f")/$(basename "${f// /_}")"; done
    - name: Remove non-related content files to this project
      run: |
        python ./.github/workflows/copy_instance_content_remove_non_related_content.py ./ ./instance_content_new
    - name: Commit files
      continue-on-error: true
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A 
        git rm --cached looker.ini
        git commit -m "Updating repo with content changes detected"
        git push 
