name: Deploy

on:
  workflow_dispatch: 
    #These inputs will guide the deploy workflow to determine where LookML and Content needs to be deployed to from this git repo
    inputs:
      instance:
        description: 'Select Instance to Deploy To: saleseng'
        required: true
      commit:
        description: 'Select Commit to Deploy'
        required: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      project: demo_github_actions_deployer
    strategy:
      matrix:
        python-version: [3.8]
        ruby-version: [2.6]

    steps:
    - name: Checkout the master branch
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
  
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    
    - name: Install Gazer
      run: gem install gazer
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Looker Deployer
      run: |
        python -m pip install --upgrade pip
        pip install looker-deployer
        pip install looker-sdk
        pip install GitPython
    
    - name: Create Looker ini File
      run: |
          cat << EOF > looker.ini
          [profservices]
          base_url=https://profservices.dev.looker.com:19999
          client_id=${{ secrets.PROFSERVICES_CLIENT_ID }}
          client_secret=${{ secrets.PROFSERVICES_SECRET }}
          verify_ssl=True 
          
          [saleseng]
          base_url=https://saleseng.dev.looker.com:19999
          client_id=${{ secrets.SALESENG_CLIENT_ID }}
          client_secret=${{ secrets.SALESENG_SECRET }}
          verify_ssl=True 
          EOF
  
    - name: Get latest workflow files
      #This step ensures the latest workflow files are available even if workflow files are updated after the code was previously deployed
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git branch -a
        git switch ${{ github.event.inputs.instance }} 
        git checkout master -- ./.github/workflows/
    
    - name: Delete old content
      #Based on git diff this will attempt to delete dashboards and looks in upstream environment
      run: |
        python ./.github/workflows/deploy_delete_content.py ./ ${{ github.event.inputs.commit }} ${{ github.event.inputs.instance }} ${{ env.project }}

    - name: Obtain new lookml content code
      #This will delete old environment branch and create it from the commit specified
      run: |
        git switch master
        git branch -D ${{ github.event.inputs.instance }}
        git checkout -b ${{ github.event.inputs.instance }} ${{ github.event.inputs.commit }}
        git checkout master -- .github/workflows/
    
    - name: Update environment variables
      #This will update lkml files for variables that are specific in each environment
      run: |
        python ./.github/workflows/find_and_replace.py ${{ github.event.inputs.instance }}
  
    - name: Commit refreshed environment branch
      run: |
        git add -A || echo "ignore commit failure, proceed"
        git commit -m "Updating ${{ github.event.inputs.instance }} with latest commits" || echo "ignore commit failure, proceed"
        git push --set-upstream origin ${{ github.event.inputs.instance }} --force || echo "ignore commit failure, proceed"
  
    - name: Deploy looker code to instance
      #This runs advanced deploy in the specified environment
      run: |
        python ./.github/workflows/deploy_lookml_code.py ${{ github.event.inputs.instance }} ${{ env.project }}
    
    - name: Add spaces in file and directory names from exported content
      #Ldeploy deploys content based on the local directories folder names so need to add in spaces for underscores
      run: |
        find -wholename "./instance_content/*_*" -print0 | sort -rz | while read -d $'\0' f; do mv -v "$f" "$(dirname "$f")/$(basename "${f//_/ }")"; done
    
    - name: Deploy content to instance
      run: |
        ldeploy content import --env ${{ github.event.inputs.instance }} --ini looker.ini --folders ./instance_content/Shared --recursive
